# profile (sql Or mongodb)
spring:
  profiles:
    active: sql

---
# SQL Profile Configuration
spring:
  config:
    activate:
      on-profile: sql
  application:
    name: Cricket-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/crickdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
# MongoDB Profile Configuration
spring:
  config:
    activate:
      on-profile: mongodb
  application:
    name: Cricket-App
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cricketdb
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "*"
