spring:
  application:
    name: Cricket-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/crickdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"


